{
 "title": "SynergyChat – Production Overview",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Too Many Req (429) for all Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "forward",
     "expr": "sum by (pod) (\r\n  count_over_time({namespace=\"default\"} |= \"429\" [5m])\r\n)"
    }
   ]
  },
  {
   "title": "HTTP 5xx Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({namespace=\"default\"} |~ \"5[0-9]{2}\" [5m]))"
    }
   ]
  },
  {
   "title": "Pod Restart Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{pod=~\"synergychat-web.*\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Rate Request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_total[1m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"synergychat-web.*\"}[1m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Replicas",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{deployment=\"synergychat-web\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}